added plot() method in advanced_2.
MarcoRiggirello/cmepda-assignments pull request #15
Opened 2021-10-21 16:57 UTC by MarcoRiggirello

Ho aggiunto l'opzione `draw_line` nel caso non si voglia plottata anche l'interpolazione; mi sembra una cosa ragionevole

2021-10-21 17:03 UTC, MarcoRiggirello commented
Volendo potremmo anche riflettere su come rendere più generale il metodo, magari evitando di chiamare `plt.show()` o evitando di impostare il titolo predefinito o i label. Magari "l'utente" vuole plottare altre cose... non so, riflettiamoci.

2021-10-21 20:25 UTC, AntuVenciu requested changes
Ho elencato cinque punti circa di miglioramenti che suggerisco o che sono necessari.

2021-10-21 20:25 UTC, AntuVenciu commented on advanced-2/advanced_2.py
> +            plt.plot(xx, self(xx), linestyle="-", marker=" ")
1) Aggiungiamo import in cima al modulo?
2) Per il resto direi ok, chiamerei l'opzione invece di draw_line ---> draw_spline;
3) Mancano le unità di misura sugli assi, per ora ci metterei '[u.a.]';
4) Credo che l'argomento 'ax' che l'assegnamento chiede sia quello necessario ad associare il plot ad una figura.

Problema più grosso, ma forse merita una issue a parte: l'assegnamento chiede che le impostazioni del plot siano definite dall'utente stesso, non predefinite come le nostre. Questo credo si faccia con un wrapper alla funzione plot di matplotlib.

2021-10-22 13:06 UTC, MarcoRiggirello commented
Allora, per quanto riguarda lasciare all'utente le specifiche basta aggiungere agli argomenti del metodo `*args, **kwargs` e abbiamo fatto. Per quanto riguarda invece la scelta di matplotlib.pyplot.plot() oppure matplotlib.pyplot.Axes.plot() forse è meglio parlarne in videochiamata...

2021-10-26 17:59 UTC, MarcoRiggirello commented
@AntuVenciu ora dovrebbe andare. Ho usato la notazione compressa di matplolib.pyplot.plot per passare le solite opzioni (colore, ecc...) sia ai punti sperimentali che alla spline. 

[https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html](url) 

guarda la sezione "Plotting multiple sets of data", ho usato la "third way"

2021-10-28 16:10 UTC, merged

2021-10-28 16:11 UTC, AntuVenciu commented
Va bene!